### ISSUE TITLE
It won't work with Google Tag Manager

### ISSUE THREAD

**Issue by naddika** [ZitRos/save-analytics-from-content-blockers#14]
In your article Google Analytics is described. 
Google Tag Manager now replaces Google Analytics and is different. GTM first load a js file. That js file then loads "google-analytics.com/analytics.js".

However, there's no difrect link to "google-analytics.com/collect" in `analytics.js` anymore. Instead there're different kinds of other links to:

 * "/r/collect"
 * https://stats.g.doubleclick.net/j/collect
 * etc...

Which ones should be proxied? Which ones not?

How to work with all that now?

**Comment by naddika** [comment]
I'd say, create a 2nd article.

**Comment by ZitRos** [comment]
@naddika haha, good suggestion! Thanks!

But allow me to express that the 2nd article would be 80% of the previous one, hence it makes little sense. Either you work with Google Analytics or Google Tag Manager, the approach stays the same.

**Comment by ZitRos** [comment]
> However, there's no difrect link to "google-analytics.com/collect" in analytics.js anymore. Instead there're different kinds of other links to:

To sum up your question above, the solution in this repository doesn't look for `google-analytics.com/collect` anymore, but it looks for patterns like those which you mentioned:

> "/r/collect"
> https://stats.g.doubleclick.net/j/collect
> etc...

...and replaces them!

**Comment by ZitRos** [comment]
[Here are the exact rules](https://github.com/ZitRos/save-analytics-from-content-blockers/blob/master/config.js) it uses.

**Comment by naddika** [comment]
Thx

**Comment by ZitRos** [comment]
U r welcome :)

**Comment by naddika** [comment]
Actually, I don't understand how it works now.

Previously the proxied url to Google Analytics would be replaced in the **inline** javascript code, **manually** by hands, to our own proxy server. All is clear.

But now for Google Tag Manager

a) there's no inline js code with any url to be proxied
b) there're multiple urls to be proxied

Yes, I've seen the code. But how should a project be **set up** then?

**Comment by ZitRos** [comment]
@naddika did you read [README](https://github.com/ZitRos/save-analytics-from-content-blockers#how-does-it-work) of this repository?

**Comment by ZitRos** [comment]
@naddika or you mean **set up** infrastructure for proxying?

**Comment by naddika** [comment]
> @naddika did you read [README](https://github.com/ZitRos/save-analytics-from-content-blockers#how-does-it-work) of this repository?

Yes. This is what you have in there

```
    <!-- Google Tag Manager Setup (a script which loads other analytics tools) -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '/www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); // When you're done setting up URL forwarding, prefix /www.googletagmanager.com/... path with your proxy route (/gtm-proxy)
    })(window,document,'script','dataLayer','GTM-XXXXXXX');</script> <!-- Replace GTM-XXXXXXX with your tag -->
    <!-- End Google Tag Manager Setup -->

```

And that's not how Google Tag Manager looks now. Your version is old. The newer version looks like this:


```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123456-7"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-123456-7');
</script>
```

**Comment by naddika** [comment]
And also, `https://www.googletagmanager.com/gtag/js?id=UA-123456-7` has no URLs that should be proxied. Instead, it loads `google-analytics.com/analytics.js` which does have URLs that should be proxied.

**Comment by ZitRos** [comment]
> Your version is old. The newer version looks like this:

Ah, now I understand! It takes a bit to make a great issue explanation! :)

So you actually want to say that the "old way of adding Google Tag Manager" doesn't work anymore, and I should re-run this repository to see what's wrong, right?

**Comment by naddika** [comment]
Yes

**Comment by ZitRos** [comment]
@naddika, just checked. Well, everything works fine with GTM... 

![image](https://user-images.githubusercontent.com/4989256/67117553-a6d38780-f1eb-11e9-8567-f4f26a997914.png)

Maybe in 

```
<!-- Google Tag Manager Setup (a script which loads other analytics tools) -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '/www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); // When you're done setting up URL forwarding, prefix /www.googletagmanager.com/... path with your proxy route (/gtm-proxy)
    })(window,document,'script','dataLayer','GTM-XXXXXXX');</script> <!-- Replace GTM-XXXXXXX with your tag -->
    <!-- End Google Tag Manager Setup -->
```

you just forgot to replace `GTM-XXXXXXX` to your tag?

**Comment by naddika** [comment]
@ZitRos  You checked code with the your old version of GTM. Why wouldn't it work?

**Comment by ZitRos** [comment]
> So you actually want to say that the "old way of adding Google Tag Manager" doesn't work anymore

> Yes

> I'm talking abount the new version of GTM.

@naddika ...

Okay, I will check the new version soon!

**Comment by ZitRos** [comment]
> The newer version looks like this:

@naddika where to see this "new version"? Google Tag Manager still suggests me to use the "old" way:

![image](https://user-images.githubusercontent.com/4989256/67163185-a5819680-f374-11e9-91bb-3853856f6560.png)

**Comment by ZitRos** [comment]
Ah, time-wasting.

@naddika, you didn't read [README](README) properly. Or didn't I described this well? Your "new" code doesn't work because you request a script directly from `www.googletagmanager.com` at the very beginning (obvious from a very basic HTML knowledge). Readme says this (as well as the example shipped in this repository):

> Modify your front end Google Tag Manager / Google Analytics script to request the proxied file

This means you have to modify your "new" script to use your proxy path, e.g. `/www.googletagmanager.com/gtag/js?id=UA-123456-7` instead of `https://www.googletagmanager.com/gtag/js?id=UA-123456-7`:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="/www.googletagmanager.com/gtag/js?id=UA-123456-7"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-123456-7');
</script>
```

If you use proxy sub-path, for example, `/gtm-proxy`, change the initial script URL accordingly to request `/gtm-proxy/www.googletagmanager.com/gtag/js?id=UA-123456-7`.

Hope this helps! Let me know if not.

**Comment by ZitRos** [comment]
I've [updated](7de00b6e0ad5852e9a2c15bbf87bcf8266819272) the README to clarify these questions. Thanks!

**Comment by naddika** [comment]
Then my version of GTM is the old one :)

**Comment by naddika** [comment]
My version wasn't Google Tag Manager but "Global Site Tag (gtag.js)". 

"Global Site Tag" replaces  Google Tag Manager 

"
The Global Site Tag provides streamlined tagging across Google’s site measurement, conversion tracking, and remarketing products – giving you better control while making implementation easier. By using gtag.js, you will be able to benefit from the latest dynamic features and integrations as they become available. 
"

**Comment by naddika** [comment]
Therefore, the issue is still open

> This means you have to modify your "new" script to use your proxy path, e.g. /www.googletagmanager.com/gtag/js?id=UA-123456-7 instead of https://www.googletagmanager.com/gtag/js?id=UA-123456-7:

No. *The way* Global Site Tag works is different from GTM.  

Go load the actual script at "https://www.googletagmanager.com/gtag/js?id=UA-NNNNNN-N"  and check if *that* works the same way Google Tag Manager does. It won't. And you'll see what I've been talking about.

**Comment by ZitRos** [comment]
I love you've started the issue from one question, and after a lengthy discussion it turns out to be a completely different question ♥ But we've nailed it!

> No. The way Global Site Tag works is different from GTM.

At the first glance, it is not different. Do not state that until you clearly understand the problem ^^

> Go load the actual script at "https://www.googletagmanager.com/gtag/js?id=UA-NNNNNN-N" and check if that works the same way Google Tag Manager does. It won't. And you'll see what I've been talking about.

So I went and checked. Everything works just fine if we ignore SSL errors on localhost. **Please remember to always describe what exactly doesn't work for you**, as it takes time to guess every time.

![image](https://user-images.githubusercontent.com/4989256/67194710-4e290800-f400-11e9-8b5e-b8252aaa24f8.png)

Note that on `localhost` there is no `https` set up, and the script fails because it requests analytics through the secure connection `https://localhost/www.google-analytics.com/analytics.js` (note `https`). Your proxy path-forwarding should handle https forwarding and request the NodeJS proxy via **http only**. To make it work on localhost, if it's your case, you can cheat a little with the config file like this:

```
        specialContentReplace: { // Special regex rules for domains
            "www.googletagmanager.com": [
                {
                    regex: /https/g,
                    replace: "http"
                }
            ],
            "www.google-analytics.com": [
                {
                    regex: /https/g,
                    replace: "http"
                }
            ],
```

Please describe what exactly doesn't work for you or was it your case. Hope this helps. Please, describe issues in very much detail, because it takes time to dig in and understand why you asking.

**Comment by naddika** [comment]
> So I went and checked. Everything works just fine if we ignore SSL errors on localhost. Please remember to always describe what exactly doesn't work for you, as it takes time to guess every time.



1. Do you have a  with a real Global Site Tag? Have you tested **that**?

2. Or have checked merely a local website -- that on localhost requests **aren't getting filtered by AdBlock**? 

Question:
is your data actually getting delivered to your Global Site Tag and appear in Google dashboard panel? It won't because, as I've said, Global Site Tag uses a different approach. What approach -- see my first messages.

**Comment by ZitRos** [comment]
> 1. Do you have with a real Global Site Tag? Have you tested **that**?

No, I don't have a "real" website with Global Site Tag, but technically the approach looks really similar and there should be no problems. And yes I have tested with your "new" code but my tag:

![image](https://user-images.githubusercontent.com/4989256/67217293-28febe80-f42d-11e9-861c-c5a229c34199.png)

> Or have checked merely a local website -- that on localhost requests aren't getting filtered by AdBlock?

I have AdGuard which is the most aggressive ad-blocking software I found, and yes it works on localhost. My screenshot of requests is made with AdGuard turned on.

> is your data actually getting delivered to your Global Site Tag and appear in Google dashboard panel?

Yes.

> Global Site Tag uses a different approach. What approach -- see my first messages.

Please explain which approach. Again, technically, I don't see the difference. Please admit that the original approach is the one which the article explains (you manually go and replace something in scripts), but the approach I am talking about here, as well as one mentioned in the article, is running NodeJS back end from this repository which does all required replacements on-the-fly automatically. The only thing you have to replace is HTML initial script to reference this back end as explained above.

**Comment by naddika** [comment]
Okay, I'll double check.
