### ISSUE TITLE
Help needed with Step 3: Implementing the Simplest Proxy Server

### ISSUE THREAD

**Issue by Sweepr** [ZitRos/save-analytics-from-content-blockers#17]
Hey there,

I tried to follow your tutorial on https://www.freecodecamp.org/news/save-your-analytics-from-content-blockers-7ee08c6ec7ee/

And i managed to get things running but i'm stuck at **Step 3: Implementing the Simplest Proxy Server**

When i browse to http://my-ip/index.html 

I get:

```
Proxied: www.google-analytics.com/r/collect?v=1&_v=j80&a=1503182168&t=pageview&_s=1&dl=http%3A%2F%2Fipremoved%2F&ul=en-us&de=UTF-8&dt=Google%20Analytics%20Test%20Proxy&sd=24-bit&sr=1920x1080&vp=1034x898&je=0&_u=AACAAEAB~&jid=1401297639&gjid=114978947&cid=88200760.1581435787&tid=UA-removed-1&_gid=1603874559.1581435787&_r=1&z=2065047711&uip=maskedip
Proxied: www.google-analytics.com/analytics.js
```
So it seems to be running.

Problem i get stuck is this: 
**Gathering all the files in the example together (see GitHub), we should end up with the following JavaScript server code:**
```
var express = require("express"), 
    proxy = require("express-http-proxy"), app = express();

app.use(express.static(__dirname)); // serve static files from cwd

function getIpFromReq (req) { // get the client's IP address
    var bareIP = ":" + ((req.connection.socket && req.connection.socket.remoteAddress)
        || req.headers["x-forwarded-for"] || req.connection.remoteAddress || "");
    return (bareIP.match(/:([^:]+)$/) || [])[1] || "127.0.0.1";
}

// proxying requests from /analytics to www.google-analytics.com.
app.use("/analytics", proxy("www.google-analytics.com", {
    proxyReqPathResolver: function (req) {
        return req.url + (req.url.indexOf("?") === -1 ? "?" : "&")
            + "uip=" + encodeURIComponent(getIpFromReq(req));
    }
}));

app.listen(1280);
console.log("Web application ready on http://localhost:1280");
```
Were should i place this code or what should i do with this code?

**Comment by ZitRos** [comment]
Hello!

Thank you for reaching out.

Answering your question, this code actually is a javascript (NodeJS) code that serves the thing that works for you. This is just a demonstration app which meant to demonstrate the proxying capabilities using JavaScript but surely not for the production use.

In this repository you'll find the production-ready containerized (and not) application which does the proxying so you (probably) don't need to code it yourself. Just check the readme of this repo.

I hope it helps! Please let me know whether it resolves your question.

**Comment by Sweepr** [comment]
@ZitRos,

Thanks for taking time to respond to my question.

What you are saying is that i don't need to use this javascript (NodeJS) code from the tutorial, but rather just use the git repo as is and it should work without adjustments? 

The default config uses port 80, i had to change that into 8084 since Apache is running on 80.

Since i really like the idea and know for a fact i'm losing out on data because of adblockers i would like to see this implemented on my server, is it possible to get this production , what else do i need to adjust in order to run this on my webserver?

Thanks in advance!

**Comment by ZitRos** [comment]
There are a couple of ways both described in readme [here](https://github.com/ZitRos/save-analytics-from-content-blockers#google-tag-manager-google-analytics-proxy), basically,

1. You either run a containerized application provided in this repository and redirect `/analytics` from the front end to it or
2. You run the application somewhere without container and again redirect traffic to it. There is an example, you can try launching it.

In case of Apache, redirecting the traffic is just a matter of setting up mod_proxy to point to the NodeJS app you run from this repo, either in a container or plain NodeJS app.

There are no detailed instructions how to make your particular setup, only ready-to-go app and a demo you can run locally - but once you understand the concept, with the help of Internet you'll be able to make a right set up for your case.

Hope that clears things out! Let me know.

**Comment by Sweepr** [comment]
Thank you for the explanation, i will study this and go from there, porbably with some trial and error i will figure it out.

For now i will close this as it's no a real issue.

Thanks again!

**Comment by ZitRos** [comment]
Yep, thanks!

Start with just running this repo locally, it should be super easy (described in readme). Then try setting up a rule for Apache to redirect traffic from a particular url (e.g. `/analytics`) to this app and it should go smooth.

**Comment by Sweepr** [comment]
Hello @ZitRos , sorry to bother you once again, but i've managed to get it running, i was just overthinking things to diffcult ;-)

Anyway i got it working, except for one problem:

In my .htaccess i made this rule for forward all requests to /analytics into the Proxy app.

```
RewriteEngine On
RewriteRule ^analytics/(.*) http://myip:8084/$1 [P]
```
But:

My the DEV window in the browser i get this response.

```An error occurred:: SSL_ERROR_RX_RECORD_TOO_LONG```

The request seems to be forced into https://, instead of http:// (which is working), not sure if that's the reason but i'm behind Cloudflare and to my knowledge all requests to http:// are forced into https://

Any idea's on how to overcome this, does the webserver have an SSL option built in?

**Comment by Sweepr** [comment]
> 
> 
> Hello @ZitRos , sorry to bother you once again, but i've managed to get it running, i was just overthinking things to diffcult ;-)
> 
> Anyway i got it working, except for one problem:
> 
> In my .htaccess i made this rule for forward all requests to /analytics into the Proxy app.
> 
> ```
> RewriteEngine On
> RewriteRule ^analytics/(.*) http://myip:8084/$1 [P]
> ```
> 
> But:
> 
> In the browsers DEV window i get this response.
> 
> `An error occurred:: SSL_ERROR_RX_RECORD_TOO_LONG`
> 
> The request seems to be forced into https://, instead of http:// (which is working), not sure if that's the reason but i'm behind Cloudflare and to my knowledge all requests to http:// are forced into https://
> 
> Any idea's on how to overcome this, does the webserver have an SSL option built in?

Disabling Automatic HTTPS Rewrites fixed that.

Automatic HTTPS Rewrites helps fix mixed content by changing “http” to “https” for all resources or links on your web site that can be served with HTTPS.

**Comment by ZitRos** [comment]
Great that you've found the solution!

Conceptually, the container (application) in this repo is designed to handle http requests, and all the SSL magic should happen before that, in your case within the Apache proxy.
