### ISSUE TITLE
[Question]: Github static gh-pages

### ISSUE THREAD

**Issue by matt77hias** [ZitRos/save-analytics-from-content-blockers#18]
Is there a way to prevent Google analytics being blocked by ad blockers for static gh-pages without requiring a server-side solution?

**Comment by ZitRos** [comment]
Hello! Thanks for your question.

Currently, you still need to run the back end for it. While quite soon (in a month), we're launching [DataUnlocker](https://dataunlocker.com/). With DataUnlocker, you won't need a back end anymore, but you will still need a control over the domain you host your website on (i.e. you will need to add a DNS record to your domain). If your website is hosted on GitHub but **has a custom domain** which you own, that's perfectly fine for DataUnlocker. If not - please let us know - we have a plan to eventually make it possible even without the custom domain (and for free), so we can prioritize it accordingly.

Anyway, you can subscribe [on the landing page](https://dataunlocker.com/#subscribe) to get an email notification once DataUnlocker goes live. Our pricing is very affordable: if it's a small website with a few users, you won't need to ever pay for it. Beyond that, it's a cheap pay-as-you-go solution.
