### ISSUE TITLE
uBlock Origin Blocking */gtag/js*

### ISSUE THREAD

**Issue by instazackwu** [ZitRos/save-analytics-from-content-blockers#19]
I use uBlock Origin, and after testing my implementation, it looks like this won't work for any adblocker that uses https://easylist.to/easylist/easylist.txt because it has a filter for `/gtag/js`?

I masked my googletagmanager URL using `npm run mask www.googletagmanager.com/gtag/js?id=XYZ`
and I have a reference to that in my app's javascript 

![adblock_network_calls](https://user-images.githubusercontent.com/39970089/93828035-61031880-fc1f-11ea-9c1a-c97558580269.png)

In the network calls, it redirects from the mask to http://MY-DOMAIN/www.googletagmanager.com/gtag/js?id=XYZ&l=dataLayer&cx=c which then gets blocked by uBlock Origin. 

Not sure if this is anything that can be addressed on the implementation side, but just wanted to report this since I saw from https://github.com/ZitRos/save-analytics-from-content-blockers/issues/14#issuecomment-544560089 that @ZitRos you use AdGuard (tracking works when I enable AdGuard instead of uBlock Origin)

**Comment by ZitRos** [comment]
Hi! Thanks for the feedback.

Try adding `/gtag/js` [here](https://github.com/ZitRos/save-analytics-from-content-blockers/blob/994e83a2d3f62269e3a25816cd767d0166b404f9/config.js#L87) and let me know if it worked.

Thinking of the issue, it's strange that the URL is a plain "http://MY-DOMAIN/www.googletagmanager.com/gtag/js?id=XYZ&l=dataLayer&cx=c" and `www.googletagmanager.com` wasn't masked. This NodeJS app will replace everything what's found in the proxied body or headers which matches [this list](https://github.com/ZitRos/save-analytics-from-content-blockers/blob/994e83a2d3f62269e3a25816cd767d0166b404f9/config.js#L26). If you can read the JavaScript code response from the first call to masked `www.googletagmanager.com/gtag/js?id=XYZ`, can you Ctrl+F "www.googletagmanager.com" there? Was you modifying [config.js](https://github.com/ZitRos/save-analytics-from-content-blockers/blob/master/config.js) anyhow?

**Comment by instazackwu** [comment]
Hm, interesting - I'm just using the docker image `image: zitros/analytics-saviour` which I see is 3 months old which should include that mask. When I look at the JS response from the first call, I see "www.googletagmanager.com" which doesn't seem correct?

I'll try adding /gtag/js to the maskPaths and will let you know how that goes.

**Comment by ZitRos** [comment]
Yes, that's strange it wasn't masked in response. I'll check tomorrow, thanks for reporting.

**Comment by instazackwu** [comment]
No problem, thanks for the fast response! 

Strangely, when testing on my local, adding in `"/gtag/js/",`  to `maskPaths` also seems to not work - here are the references in the JS response to from the first call:

```return null},yd=!1;if(H.querySelectorAll)try{var Bd=H.querySelectorAll(":root");Bd&&1==Bd.length&&Bd[0]==H.documentElement&&(yd=!0)}catch(a){}var vd=yd;var Pd={},L=null,Qd=Math.random();Pd.B="UA-177778100-1\x3e";Pd.Sb="990";Pd.Mh="";var Rd={__cl:!0,__ecl:!0,__ehl:!0,__evl:!0,__fal:!0,__fil:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0},Sd={__paused:!0,__tg:!0},Td;for(Td in Rd)Rd.hasOwnProperty(Td)&&(Sd[Td]=!0);var Ud="localhost/www.googletagmanager.com/*(Z3RtLmpz)*";Ud="localhost/www.googletagmanager.com/gtag/js";
var Vd=Ud,Wd=null,Xd=null,Yd="//localhost/www.googletagmanager.com/a?id="+Pd.B+"&cv=1",Zd={},$d={},ae=function(){var a=L.sequence||1;L.sequence=a+1;return a};
var ej=function(a,b,c,d){function e(){var f={config:a,gtm:ki()};c&&(vf(d),f.auiddc=rf[sf(d.prefix)]);b&&(f.loadInsecure=b);void 0===F.__dc_ns_processor&&(F.__dc_ns_processor=[]);F.__dc_ns_processor.push(f);Pc((b?"http":"http")+"://localhost/www.googletagmanager.com/dclk/ns/v1.js")}sd(D.o)?e():od(e,D.o)},fj=function(a){var b=/^u([1-9]\d?|100)$/,c=a.getWithConfig(D.ue)||{},d=gi(a),e={},f={};if(Va(c))for(var h in c)if(c.hasOwnProperty(h)&&b.test(h)){var k=c[h];g(k)&&(e[h]=k)}for(var l=0;l<d.length;l++){var p=
encodeURIComponent(d.containerId)+"&l=dataLayer&cx=c",k=("http:"!=F.location.protocol?"http:":"http:")+("//localhost/www.googletagmanager.com"+h),l=Xh(c,h)||k;Pc(l)}}}},dk=function(a,b,c,d){if(d.aa){var e=bk(a,d.aa),f=e.m;if(f){var h=m(c),k=m(e.targetConfig[d.aa]),l=m(e.containerConfig),p=m(e.i),n=m(a.i),r=Fe("gtm.uniqueEventId"),t=Eg(d.aa).prefix,q=fi(ei(di(ci(bi(ai($h(h),k),l),p),n),function(){ye(r,t,"2");}),function(){
(void 0===F[a]||c&&!F[a])&&(F[a]=b);return F[a]},Ol=function(a,b,c){return Ye(a,b,void 0===c?!0:!!c)},Pl=function(a,b,c){return 0===gf(a,b,c)},Ql=function(a,b){if(Hg()){b&&I(b)}else Rc(a,b)},Rl=function(a){return!!cl(a,"init",!1)},Sl=function(a){al(a,"init",!0)},Tl=function(a,b){var c=(void 0===b?0:b)?"localhost/www.googletagmanager.com/gtag/js":Vd;c+="?id="+encodeURIComponent(a)+"&l=dataLayer";W(Q("http://","http://",c))},Ul=function(a,
```

**Comment by instazackwu** [comment]
Also not sure if you're aware, but when trying to run docker build, I get this error:

```
$docker build -t test:latest -f Dockerfile .
Sending build context to Docker daemon  55.81kB
Step 1/13 : FROM alpine AS stage
latest: Pulling from library/alpine
df20fa9351a1: Pull complete
Digest: sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
Status: Downloaded newer image for alpine:latest
 ---> a24bb4013296
Step 2/13 : WORKDIR /app
 ---> Running in e3a9351f0d04
Removing intermediate container e3a9351f0d04
 ---> 078c38c035f6
Step 3/13 : COPY . /app
 ---> 5a2a8e6ea4d6
Step 4/13 : RUN apk add --update npm=12.15.0-r1
 ---> Running in 8689e3f1996b
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  npm-12.18.4-r0:
    breaks: world[npm=12.15.0-r1]
```

**Comment by instazackwu** [comment]
Just to follow up here @ZitRos , have you been able to check into this?

Thanks!

**Comment by ZitRos** [comment]
Sorry for getting back late this time: ultra-busy. Yes the problem is confirmed, need to update the NodeJS app. I'll try to do it shortly if it turns our that's easy, or you can try yourself if you are proficient in NodeJS :)





> ERROR: unsatisfiable constraints:
>   npm-12.18.4-r0:
>     breaks: world[npm=12.15.0-r1]

Haha, you can never lock a version in Docker. Love it. Thanks, will also consider fixing (just change to download latest - should be fine).

**Comment by ZitRos** [comment]
Oh, that was easy. Fixed by 8540403a9fe196500ef8425995d84a4d03f0294b.

Please verify :)

**Comment by instazackwu** [comment]
Oh that's great! Confirmed that this fixed the issue, and that this method works now with uBlock Origin.

Appreciate the help!

**Comment by ZitRos** [comment]
Great, glad to hear it works now!

Stay tuned for [dataunlocker.com](https://dataunlocker.com/)! :)
