### ISSUE TITLE
Weird behaviour: Google Analytics reports visits but realtime counter stats at zero

### ISSUE THREAD

**Issue by vitobotta** [ZitRos/save-analytics-from-content-blockers#21]
Hi! I am testing this solution to try and fix GA's stats. The idea is brilliant! :)

I am seeing something weird though. The script is proxied etc and in the realtime view of GA I can see something in "Top Pages" as I visit pages, but the "active users" counter stays at zero as if something is missing in the tracking. Any idea of how to fix? Thanks!

ps. when will the service be available?

**Comment by ZitRos** [comment]
Hello! Thanks for your question.

Indeed, this happens if the location is incorrectly overwritten (you should also see a blank map for your visit). GA takes location from the user's IP address, while during the proxy, this is the server's IP. So the proxy you have to overwrite it with `&uip=` query param.

```
2020-10-17T13:06:25.066Z proxied: www.google-analytics.com/analytics.js
2020-10-17T13:06:25.471Z proxied: www.google-analytics.com/collect?v=1&_v=j86&a=201489757&t=pageview&_s=1&dl=https%3A%2F%2Ftest.com%2F&dp=%2F&ul=en&de=UTF-8&dt=...&sd=24-bit&sr=1920x1080&vp=1059x979&je=0&_u=AACAAEAB~&jid=&gjid=&cid=xxx.xxx&tid=xxx.xxx&_gid=xxx.xxx&z=1741160766&uip=192.168.1.1
```

F.e. if you try it locally, you will see `192.168.1.1` in the logs, which is "no location". The fix depends on where you run it. If you run this container behind the other proxy, ensure it applies all [wanted headers](https://github.com/ZitRos/save-analytics-from-content-blockers#proxy-in-front-of-the-proxy).

> ps. when will the service be available?

I had a habit of telling very optimistic dates, so let's put it like this: very likely by the end of this year (if you've subscribed on [dataunlocker.com](https://dataunlocker.com)).

**Comment by vitobotta** [comment]
Hi, @ZitRos!

Thanks for getting back to me so quickly :) I found the problem. It wasn't because of missing headers but because I'm in Kubernetes with a Load Balancer in front of the Nginx ingress controller, so the IP seen by the proxy was the IP of the LB.

I have updated the Nginx config to use that IP as a whitelisted LB so now Nginx, and thus the proxy can see the actual IP of the client. So it seems to be working now! I can't wait to see the difference in the stats. I am also using Umami alongside Google Analytics, but Analytics has a lot more features so if I can work around ad blockers it would be awesome. Hopefully, this is the fix :)

As for your service, sounds great. The only thing that concerns me and probably others is that if a malicious third party manages to gain access to your systems, they might be able to inject scripts into your customers' websites, right? So it's kinda a trust issue where e-commerce sites are concerned because of the collection of credit cards etc. What do you think about this and what are you doing to prevent it from happening? I will likely be a customer when this is ready so I am very interested to know about security. Thanks!

**Comment by vitobotta** [comment]
@ZitRos,

I found a problem: now the location is correct but GA's IP filters no longer work. It's no longer ignoring visits from my home IP. Is there a workaround for this? Thanks!

**Comment by ZitRos** [comment]
You're welcome! Glad it's fixed.

> if a malicious third party manages to gain access to your systems, they might be able to inject scripts into your customers' websites, right?

Right, because we proxy stuff (and scripts). While it shouldn't be surprising, it's like with any other SaaS: in order to use it you have to trust it. From the customer's perspective, we are surfacing different (and by the way quite robust) monitoring tools & access control to mitigate this. If you have any other ideas of what else can we do to make it feel safe, you're welcome to share them.

> I found a problem: now the location is correct but GA's IP filters no longer work.

Do you see your IP address in the proxy's container logs? (i.e. `&uip=<your ip here>`) If you do, that's not the problem with the proxy container itself, perhaps, with Google Analytics not accounting for the IP overwrite when filtering requests.

**Comment by vitobotta** [comment]
Thanks for the explanation. 

Yes, I see my IP in the "uip" parameter now. Surprised if Google doesn't honor the filters when the IP is overridden.

Anyway, I'm closing. Thanks for your help! Will see over the next few days how it goes. In theory, I should see similar stats to those of Umami. :)

**Comment by vitobotta** [comment]
So it looks like the issue is because the IP specified with uip is always anonymized, so any straight comparison with an IP will fail and that's why the filters do no work in this case. However, we can send custom metrics to Google and use those custom metrics in the filters. 

Would it be possible for you to add an environment variable that allows us to specify a comma separated values list of IP addresses to ignore, and then send some custom metrics like _ignored_ip1_, _ignored_ip2_ etc with the relevant values, so that we can use these custom metrics in the filters in GA? That would be awesome. I would like to help but I am not familiar with node etc. Thanks!

**Comment by vitobotta** [comment]
For reference https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#uip

**Comment by vitobotta** [comment]
I found a workaround! Since the IP is anonymized, the last octet is set to 0. So I just changed the filter to have the 0 for the last octet. It seems to work because it's not tracking visits from my home IP address. This is fine for me since it's not likely to happen often that someone with almost identical IP as mine would visit :D

**Comment by ZitRos** [comment]
> It seems to work because it's not tracking visits from my home IP address.

Nice! I suspect this solution is enough and should not be coded into the container. Anyway, the upcoming SaaS uses a bit different proxying approach (and totally different code) from this open-sourced thing. Feel free to close the issue if it's resolved. Thanks!

**Comment by vitobotta** [comment]
Yep, I agree that this workaround is enough, at least for me. Closing. 

BTW super quick post about it https://vitobotta.com/2020/10/17/google-analytics-proxy/ :)

**Comment by ZitRos** [comment]
Wow, thank you! I really appreciate people who write blogs and articles. I also [do](https://www.freecodecamp.org/news/author/zitro/) [write](https://medium.com/@zitro) myself, however, lately I started to have just a few free minutes to write. I am looking towards resuming my writing again, soon ☺

Have a great day!

**Comment by vitobotta** [comment]
Wow just saw the post on your blog on GA and ad blockers. You did this 3 years ago already? I should have looked for this kind of solution before. BTW I can already see a difference in the visits tracked compared to before 👍 

There still is a little difference between GA and Umami (Umami tracks a little more visits) but that might be because GA perhaps has better filters for bots.

**Comment by ZitRos** [comment]
Yeah, 3 years ago... :) Good news that you can see a difference!

> There still is a little difference between GA and Umami

I'm curious, what's the difference in %? I didn't try Umami, but from quickly reading through [this page](https://umami.is/docs/tracker-config) it seems that it works using the same principles as GA. Bots, however, might make a difference, as well as "quick page visits", when the user bounces before one of the scripts reports analytics data (somewhen between ~2-6s of viewing the page; who knows, but you can try swapping the GA/Umami scripts with `defer` attribute in place, if Umami was the first one in the html code).

**Comment by vitobotta** [comment]
It's a small difference. For example for my personal blog, so far today Umami says 194 visitors and 249 page views, while GA says 185 users, 197 sessions, 238 page views. GA uses cookies so it tracks unique users and sessions differently. Umami doesn't use cookies so the comparison might be more between GA sessions vs Umami users. Although it's weird that this way GA reports one more visit but 11 fewer page views. Boh. Anyway, before the difference was MUCH bigger, like 40-50% or something.

**Comment by ZitRos** [comment]
Yay, 40% is huge! Thanks for sharing. I guess ad blockers will soon get to Umami anyway, if it uses recognizable URL patterns (like `/umami.js`) :)

Precision is quite close, that's nice. Though I never expect client-side analytics to be very precise, always allowing for a little some error of f.e. untracked strange cases when users open the page and close it before the analytics scripts are loaded or events are submitted.

**Comment by vitobotta** [comment]
When  Cloudflare announced a revamped version of their server-side analytics I tried it right away and was so disappointed. It counted so much stuff that it should ignore instead, so I canceled after some testing. They are also going to release public and free javascript-based version in the future.

**Comment by ZitRos** [comment]
Good to know. I am also excited by Google Analytics 4, and their analytics UI redesign. Much more tidy.
