### ISSUE TITLE
Which third party scripts do you need help with?

### ISSUE THREAD

**Issue by austincollinpena** [ZitRos/save-analytics-from-content-blockers#22]
I'm pretty motivated to get this working for a GTM set up. Where can I see the scripts you've already got this working with?

Outside of setting X-Real-IP, X-Forwarded-For and "uip," is there anything else that needs to be done for IP address forwarding?

**Comment by ZitRos** [comment]
Hello! Thanks for your interest. Glad to hear!

> Where can I see the scripts you've already got this working with?

I recently had it on my own websites, but now I switched to [dataunlocker.com](https://dataunlocker.com/) there, which is coming out soon (read: testing). But there are some quite crowded websites who are happily using container already (I'm not sure whether it will be correct to mention them here). As you can guess from the number of stars of this repository, it is quite used!

So far, including those who are using this container (which also were including myself), I heard no issues so far. It is fully about GTM + GA, and the setup has no known problems yet except the solved ones you already mentioned:

> Outside of setting X-Real-IP, X-Forwarded-For and "uip,"

One of my fears was rate limiting, but Google Analytics / GTM does not impose it (this is also documented).

**Comment by austincollinpena** [comment]
> GTM + GA, and the setup has no known problems yet except the solved ones you already mentioned:

Awesome, that answers my question, thanks!
