### ISSUE TITLE
Using path instead domain for multidomain webpages

### ISSUE THREAD

**Issue by i2dcarrasco** [ZitRos/save-analytics-from-content-blockers#3]
Hello,

I'm trying to configure this proxy to prevent the block of google scripts on my site, and finally I've made it work. All scripts are loaded from my site and url are replaced inside that files without problem.
My problem is that proxyDomain is mandatory, and I just want to use the domain where i'm doing the request.
In some files I can just leave it empty or just add the path, but when the source scripts have double slash (//) then it fails, for example //www.googleadservices.com

I don't know about JS or NodeJS and i'm was not able to fix it. Is possible?

Thanks!

**Comment by ZitRos** [comment]
Hello @i2dcarrasco!

Thanks for the feedback. You're right, `proxyDomain` is mandatory. I did this for a reason: in original scripts, usually, there's no easy way to replace `http(s)://` with `//`. The protocol is usually hidden by some javascript magic. While it's quite easy to replace domains itself, and what the proxy service does is it finds `blocked-domain-name.com` and replaces it with `proxyDomain/blocked-domain-name.com`.

So, yeah, you have to specify `proxyDomain`.

Hope that resolves your question! If not, feel free to comment or reopen the issue.

Thanks!

**Comment by i2dcarrasco** [comment]
Hello,

That's not really what I mean when I say that I want to use the request host instead a fixed host, but I've seen what you mean with your comment.
Anyway, after some time trying by trial and error, and reading about the functions that you use, I've found a way to do what I want:
`# diff proxy-original.js src/modules/proxy.js
8a9
> var currenthost = "";
22,23c23,24
<             ? config.proxyDomain.replace(/\//g, "\\/") + "\\"
<             : config.proxyDomain
---
>             ? config.proxyDomain.replace(/\//g, "\\/").replace("*(CurrentHost)*", currenthost) + "\\"
>             : config.proxyDomain.replace("*(CurrentHost)*", currenthost)
54c55
<         userResDecorator: (_, proxyResData) => {
---
>         userResDecorator: (_, proxyResData, userReq) => {
57a59
>             currenthost = userReq.headers.host;
`
With this I can use "*(CurrentHost)*" in config.js to get the current hostname:
`const proxyDomain = process.env.PROXY_DOMAIN || "*(CurrentHost)*/analytics";`

So if I ask for https://aa.com/analytics/www.google-analytics.com/analytics.js I'll get all google domains replaced by aa.com, and with https://bb.com/analytics... will be replaced by bb.com.

Surely there are better ways to do it, but my knowedge about JS and Node.js are null.

Greetings!

**Comment by ZitRos** [comment]
Ah now I see, BIG thank you for demonstrating what do you mean. Seems absolutely reasonable and doable. Once I get home I’ll try to investigate this once again.

**Comment by ZitRos** [comment]
I've implemented this within fda75ec5d55faa554c9b8bb9675d2410fb67a52c. Thanks!

I am just wondering whether this implementation is 100% compatible with your case. Because in our environment we containerize this NodeJS app and route traffic through it - all work well. Please get back if there is anything we can improve. Thanks!
